apiVersion: v1
kind: Service
metadata:
  name: odoo-production
  namespace: odoo-namespace
  labels:
    app: odoo-production
spec:
  selector:
    app: odoo-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8069
  type: LoadBalancer