apiVersion: v1
kind: Service
metadata:
  name: odoo-production
  namespace: odoo-namespace
  labels:
    app: odoo-production
spec:
  type: LoadBalancer
  selector:
    app: odoo-production
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours